version: '2'
services:
    gamesportal-app:
        image: gamesportal
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://gamesportal-postgresql:5432/gamesPortal
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    gamesportal-postgresql:
        extends:
            file: postgresql.yml
            service: gamesportal-postgresql
